Tests for store modules
xrnl/aginun pull request #117
Opened 2020-11-21 13:39 UTC by aleesaan

## What changes have been made? 
Added tests for the store modules.

### Issues resolved by these changes
Resolves #61 

## Additional comments
I also refactored the defaults store into consts, since they are static values.

2021-01-20 14:16 UTC, SamLubbers requested changes
@aleesaan I can't thank you enough for writing all the tests for all the Vuex store modules :raised_hands: :100:  I can see that this required a lot of work, especially for complex tests with Apollo queries & mutations, or the really complex `loadRoles` function.

I've ran the tests and they all pass! I only have a few questions and issues which I comment in the code and here below:

### test:unit:dev breaks

When running the command `test:unit:dev` I get the following error:

```
  ● Test suite failed to run. Configuration error:

    Could not locate module @/i18n/messages/${lang}.json mapped as:
    .../aginun/src/i18n/messages/${lang}.json.

    Please check your configuration for these entries:
    {
      "moduleNameMapper": {
        "/^@\/(.*)$/": ".../aginun/src/$1"
      },
      "resolver": null
    }
```

I assume the `loadLanguageAsync` isn't working as expected (in `src/i18n/utils/load-language-async.ts:13`)

### mock getters

When I run `test:unit` all tests pass succesfully, but I get the following error message:

```
console.error node_modules/vuex/dist/vuex.common.js:1025
  [vuex] unknown getter: user/loggedIn
```

This Vuex error appers when we test a component that needs access to a getter, but that getter is not mocked within the test. The only component we currently test that accesses user/loggedIn is `TheAppBar`, so this error is fixed by mocking the getter in `tests/unit/components/components.spec.js:43`:

```ts
    store = new Vuex.Store({
      modules: {
        user: { namespaced: true, getters: { loggedIn: () => true } },
      },
    });
```

### simpler testing code structure?

The store tests are incredibly well structured, with a `describe` block for each of the modules, and nested `describe` blocks for `mutations` and `actions`. 

Is it necessary to make a `describe` block for each of the individual mutations and actions? To me it seems redundant as each of those blocks only has one unit test. Perhaps we can remove each of those describe blocks, and start each `it` test case with the name of the module. So, for example, instead of having: 

```ts
describe("setAlert", () => {
  it("updates the alertOn and alert state", () => {
  // ...
  });
});
```

we could have

```ts
it("setAlert: updates the alertOn and alert state", () => {
// ...
});
```

Actually now that I'm reviewing the tests for the roles module I see there are some cases where you have multiple `it()` in a single `describe()` block. :see_no_evil: Would you like to continue using this structure for more clarity?

2021-01-21 17:46 UTC, aleesaan commented
> I've ran the tests and they all pass! I only have a few questions and issues which I comment in the code and here below:
> 
> ### test:unit:dev breaks
Super weird, I must have introduced it after rebasing but it was working for me, even after an `npm i`. I now tried removing the node_modules, doing another a fresh `npm i`, and I got the error. After trying a few things I found [this weird solution](https://stackoverflow.com/a/59603177/10279281) that seems to work, so I'll go for it.

> ### mock getters
Right, the error must have showed up after I rebased - I didn't think running the component tests then. Will fix it!

> ### simpler testing code structure?
Initially I had a more flat structure indeed, but once I got to the roles store tests I realized it'd be better having a proper structure. It might look more complicated now, especially for smaller store modules, but as the code grows it will be much more scalable without the need of future refactors.
> Actually now that I'm reviewing the tests for the roles module I see there are some cases where you have multiple `it()` in a single `describe()` block. 🙈 Would you like to continue using this structure for more clarity?  

I didn't read this part until after I wrote my response above 😂  you went through my thought process as well I see! I think it's indeed better to keep this structure, it's more flexible and will provide a solid architecture!

2021-01-21 18:19 UTC, aleesaan commented on src/store/modules/roles.ts
> -    async reloadRoles({ commit }) {
No 😂  `setTimeout` doesn't return a promise, I only noticed because TS complained about it, one of the reasons why you gotta love TS!

2021-01-21 18:27 UTC, aleesaan commented on tests/unit/store/groups.spec.ts
> +  const mockData = {
In theory yes (I'll get to it later), but in practice it doesn't matter for two reasons:

1. We're not using the interface in the getters yet, as adding interfaces there will require a few changes and it should be done in a separate case.
2. Even when we'll add interfaces in the getters, not specifying the type here will still be fine, as the structure (automagically inferred by TS) of the `mockState` will match the interface of the getters, so TS wouldn't complain.

Still, adding a type here will add type checking on the `mockState` object, so that if later on we try to add wrong properties to it by mistake, it will complain about it. So I will add it indeed!

2021-01-21 18:38 UTC, aleesaan commented on tests/unit/store/groups.spec.ts
> +      Promise.resolve({ data: mockData } as ApolloQueryResult<unknown>)
Yea I was having some issues with it in the roles file... Anyway I adjusted all of them and you can have a look.

2021-01-21 18:39 UTC, aleesaan commented on tests/unit/store/roles.spec.ts
> +        );
Yes but we're not testing the `Vue.set` functionality, we just need to test that it gets called with the right values. Right?

2021-01-21 18:52 UTC, aleesaan commented on tests/unit/store/roles.spec.ts
> +
Mmh no I don't think those need to be covered in unit tests to be honest. If anything, it'd be covered in functional tests when running the whole app.

2021-01-21 20:25 UTC, aleesaan commented on tests/unit/store/roles.spec.ts
> +  describe("actions", () => {
Yea because we mock the `apolloClient`, so we'd need to write a mock implementation which then calls the `commit` function...

2021-01-23 17:00 UTC, SamLubbers commented on src/store/modules/roles.ts
> -    async reloadRoles({ commit }) {
I love when linting automatically flags issues :relaxed: thanks TS <3

2021-01-23 17:23 UTC, SamLubbers commented on tests/unit/store/roles.spec.ts
> +        );
I think it depends on the function that you're calling: 

if you're calling a function that you've written, in most cases you just want to test that it's called. Otherwise you're double testing the functionality of that function. An example of this is testing that the Vuex actions call the Vuex commits.

But if you're calling a standard function, instead of just testing that you called the function, you might want to test that you're getting the right outputs for given inputs. For example, in this case when calling the commit with a given filter, the output should be to have that filter set in the store. I think we should test that this output is achieved, rather than how it is achieved. The reason we call `Vue.set` is because in Vue 2 doesn't support direct assignment of nested objects (`state.selectedFilters.search = "search string"`), but this is supported in Vue 3. So when we migrate to Vue 3 and replace all `Vue.set` calls with direct assignments this test will not work anymore (even though the application produces the right result).

I hope this explanation what somewhat clear :sweat_smile: I found it a bit hard to put all this into words.

2021-01-23 17:26 UTC, SamLubbers commented on tests/unit/store/roles.spec.ts
> +  describe("actions", () => {
yeah that seems like too much effort right now. I'll make a low-priority issue to figure out a good solution for this in the future.

2021-01-23 17:33 UTC, SamLubbers approved these changes
@aleesaan thanks for getting back to this so quickly and engaging with the feedback so well :zap:  :clap:

I'm glad you found that obscure solution on Stack Overflow for the issue with --watch tests! And yes we both went through the same thought process regarding the testing structure :joy: I think it's great to keep it like this.

I only left one comment of something that could be slightly better. But since everything else is perfect I'll go ahead and approve and merge :relieved: we can improve the rest more in the future :wink:

2021-01-23 17:34 UTC, merged