Add typescript support
xrnl/aginun pull request #119
Opened 2020-11-26 17:54 UTC by aleesaan

## What changes have been made? 

- Added support for typescript, disabling `noImplicitAny` for now to keep changes minimal
- Updated some dependencies
- Created separate config files to have a better separation of concerns
- Fixed linters as we were getting conflicts, now the code is shiny ✨ 
- Refactored store modules with static data into consts
- Moved tests files to match the folder structure suggested by the vue cli
- Left the components tests in `js` as they would require additional changes, and since we should refactor them anyway (to split them into invididual files), we can migrate them to `ts` then.

Note that most of the changes are automatic lint fixes done by the cli, especially in component files.

### Issues resolved by these changes
Resolves #107

## Additional comments
This is a follow up case to @RainnyX's [PR](https://github.com/xrnl/aginun/pull/115), which had some issues with styling, and I couldn't get it to work. I had tried improving some things in a separate [PR](https://github.com/RainnyX/aginun/pull/1), but I just couldn't solve the styling issues: I slowly downgraded the various packages, but when it still didn't work, I ended up starting from scratch and added our original changes one at the time, without upgrading vuetify-related things. We can look into upgrading vuetify (and figure out what breaks) in a later case.

2020-11-29 17:25 UTC, SamLubbers requested changes
@aleesaan and @RainnyX this change is AMAZING :heart_eyes: :heart_eyes: Richard thank you for building the foundation and Ale thank you for fixing all the issues, painstakingly installing packages one by one, and making such a clear pull request :green_heart: 

I've just finished the first part of the review, which consisted of testing the application and checking all vue and configuration files. I'm already sharing my feedback so you can implement which I do the second part of the review: checking the new typescript files.

For the configuration files I've left all my comments in the code. Here is the rest of my feedback:

## Issues

I need to admit that I was surprised the application still worked so well after all these changes :laughing: I've only encountered one issue

## Unable to create / edit roles

When I create or edit a role, I get the following error and the role doesn't create/edit: `Uncaught (in promise) Error: GraphQL error: field "timeCommitments" not found in type: 'role_insert_input'`

## Remaining functionality

I think it is really good that you're taking  a gradual approach to migrating to typescript. Is it an idea to make issues for all the parts that we still need to migrate to typescript? That way we can easily divide this work between you, Richard, me or anyone else who'd like to help.

2020-11-29 17:25 UTC, SamLubbers commented on src/store/modules/index.js
> -// https://github.com/chrisvfritz/vue-enterprise-boilerplate/blob/master/src/state/modules/index.js
I'm very happy you've deleted this horrible file that automatically loaded modules :grin: It was extremely long and hard to understand. The current manual loading of modules in `store/index.ts` is much much better :sparkles:

2020-11-29 20:59 UTC, aleesaan commented on .prettierrc.json
> +}
- In typescript we'll need to declare types for the arguments, so we'll always need brackets around function params.
- I only changed it cause I think 80 is a bit too restrictive, but I'll just drop `printWidth` altogether and just use the default (`80`).
- I only dropped them because they're already the default values.

2020-11-29 21:26 UTC, aleesaan commented
Thanks for the thorough testing and comments @SamLubbers! I've already fixed the error you mentioned about creating/editing roles 💪   
Next I'll look into the specific comments about the configs, but just as a general answer: most of the changes I did were to match the configurations generated by the vue-cli, which I think is good to follow! Still, I'll look into your comments in detail tomorrow so I can see more specifically ✌️

2020-11-30 17:28 UTC, aleesaan commented on .eslintrc.js
> +    node: true
I followed the configuration given by the vue cli, and they didn't have these. From my testing the `window` object is still working fine though, or did you notice any issue?

2020-11-30 17:43 UTC, aleesaan commented on .eslintrc.js
> +  extends: ["plugin:vue/essential", "@vue/airbnb", "@vue/typescript", "plugin:prettier/recommended"],
I had added the `airbnb` plugin as airbnb is considered a [good standard](https://github.com/airbnb/javascript) for codestyle, and because it's the first lint configuration suggested by the cli. I now removed it and went with the 'prettier' lint configuration from the cli; I still have to push, but this is how it looks:
```
"plugin:vue/essential",
"eslint:recommended",
"@vue/typescript/recommended",
"@vue/prettier",
"@vue/prettier/@typescript-eslint"
```
If that's ok with you I think it's good to follow this default configuration offered by the cli, without adding the `plugin:vue/strongly-recommended` and `plugin:vue/recommended`, both because it's good practice to follow the CLI setup (as it is thoroughly tested and consolidated) and because using multiple recommended plugins could end up causing us issues (let's say if they conflict with the recommended stuff for typescript). What do you think?

2020-11-30 17:49 UTC, aleesaan commented on CONTRIBUTING.md
> -  * Be formatted with [Prettier](https://prettier.io/). We use prettier to have a consistent and automatic code formatting without having to memorize and follow a style guide.
I'm not sure how it happened, I'll revert this change! We need to mention both prettier and eslint, they have different functionality (has explained in these paragraphs 😅).

2020-11-30 18:01 UTC, aleesaan commented on .eslintrc.js
> +    "no-console": process.env.NODE_ENV === "production" ? "warn" : "off"
Same as for the other answer, I used the default configs from the vue cli. I don't think we need the extra rules since we use the recommended ones, and I think they're working pretty great! Unless you see the edge cases that needed these rules, I'd say to leave them out. What do you think?
As for your question about the eslint in production, yes! You can already test it by adding a `console.log` somewhere and changing the `lint` script to `vue-cli-service lint --mode production`, which will then throw a warning.

2020-12-06 10:51 UTC, SamLubbers commented on .prettierrc.json
> +}
* good to know. Let's keep it that way
* yes I previously thought that it always had to be 80 but I learned this week that 120 is the new standard. This works much better for the html in our vue files
* yes good to use the default values.

2020-12-06 10:52 UTC, SamLubbers commented on .eslintrc.js
> +  extends: ["plugin:vue/essential", "@vue/airbnb", "@vue/typescript", "plugin:prettier/recommended"],
sounds good to use the recommended CLI standards. If our code really needs more quality enforcement we can add more rules in the future :+1:

2020-12-06 10:53 UTC, SamLubbers commented on .eslintrc.js
> +    node: true
no me neither, so let's go with the CLI standard.

2020-12-06 11:05 UTC, aleesaan commented on .prettierrc.json
> +}
Ah I actually dropped the `120` in the end 😅  shall I bring it back? I do think 80 is quite short!

2020-12-06 11:08 UTC, SamLubbers commented on .prettierrc.json
> +}
Yes you can bring it back 😂

2020-12-06 11:13 UTC, SamLubbers commented on .eslintrc.js
> +    "no-console": process.env.NODE_ENV === "production" ? "warn" : "off"
- good to know about the production flag on eslint. Then we can easily test that before deploying
- I think that custom configuration I added was to solve a conflict between prettier and the Vue recommended rules. Since we don't have that rule anymore we can keep it out.
- for prettier, I think it's still useful to add the warning so that it tells you what code isn't formatted right. Or maybe that isn't necessary if prettier autoformats the code. What do you think?

2020-12-06 11:26 UTC, aleesaan commented on .eslintrc.js
> +    "no-console": process.env.NODE_ENV === "production" ? "warn" : "off"
Yep it's not needed! Prettier will format automatically based on our lint rules so we don't need a warning.

2020-12-06 11:46 UTC, SamLubbers approved these changes
@aleesaan I finally managed to finsih reviewing it (on my phone, on the train on my way to the antiracism protest in The Hague).

The code looks good to merge. The js to ts changes are actually very minor; most were eslint fixes.

In future pull requests I would first make a request with all the lining fixes and then all the typescript changes. Then it's easier to see what changed.

Thanks again for this big improvement! 💯

2020-12-06 11:46 UTC, merged