Issues 121 and 122
xrnl/aginun pull request #134
Opened 2021-01-25 13:58 UTC by DenBaas

This solves #121 and #122. The only thing left is styling the login form, because I did nothing about this.
![afbeelding](https://user-images.githubusercontent.com/5918608/105715259-aad97380-5f1d-11eb-9bab-6478bb0ffabb.png)

2021-01-27 12:43 UTC, kajdehoop requested changes
@DenBaas Looks good Bas, thank you so much! 😄 

I've added a couple of comments on your code. In my local instance I had one problem, I didn't see the error messages. This was due to a CORS issue. I think this has nothing to do with your code but is due to a configuration issue on the keyserver. I'll check if we can fix that 🙂 

Great that the login can be completed by pressing the enter key! I have one other suggestion to improve the user experience: when opening the login modal, the username field should be in focus, so people don't have to click in that input field to start typing (they can then just type username -> press tab -> type password -> press enter).

I've attached the design for the login modal. Do you have some experience with CSS to finish the styling (or want to give it a try)? Or should I fix the styling for the modal?

![image](https://user-images.githubusercontent.com/51111316/105991848-970c4980-60a4-11eb-8017-54f4f398cf07.png)

2021-01-27 12:43 UTC, kajdehoop commented on src/components/layout/LoginModal.vue
> +        password: "test",
These should be initialized as empty strings, instead of the 'kaj-dev' and 'test'

2021-01-27 12:43 UTC, kajdehoop commented on src/components/layout/LoginModal.vue
> +        this.$store.dispatch("user/login", {username, password, self}).then(result => {
Why is `self` set to `this` and then send to the `user/login` action? It doesn't seem to be used there. 

Another small comment on best practices: it's best to use `let` or `const` instead of `var` for variables, as `var` is being phased out in newer JS versions. `let` is used for variables that contain a value that will later change, `const` is used for variables that contain a value that never changes. `var` can have some unexpected effects due to its scope. [Differences between var, let and const](https://www.freecodecamp.org/news/var-let-and-const-whats-the-difference/)

2021-01-27 14:04 UTC, DenBaas commented on src/components/layout/LoginModal.vue
> +        password: "test",
> 
> 
> @DenBaas Looks good Bas, thank you so much! 😄
> 
> I've added a couple of comments on your code. In my local instance I had one problem, I didn't see the error messages. This was due to a CORS issue. I think this has nothing to do with your code but is due to a configuration issue on the keyserver. I'll check if we can fix that 🙂
> 
> Great that the login can be completed by pressing the enter key! I have one other suggestion to improve the user experience: when opening the login modal, the username field should be in focus, so people don't have to click in that input field to start typing (they can then just type username -> press tab -> type password -> press enter).
> 
> I've attached the design for the login modal. Do you have some experience with CSS to finish the styling (or want to give it a try)? Or should I fix the styling for the modal?
> 
> ![image](https://user-images.githubusercontent.com/51111316/105991848-970c4980-60a4-11eb-8017-54f4f398cf07.png)

Thanks for the feedback! I can make this :)

2021-01-27 14:07 UTC, DenBaas commented on src/components/layout/LoginModal.vue
> +        password: "test",
I'm not sure why that response got there. buy anyway: we should not forget to remove this and change/remove this account for security. I'll put it back for now

2021-01-27 14:12 UTC, DenBaas commented on src/components/layout/LoginModal.vue
> +        this.$store.dispatch("user/login", {username, password, self}).then(result => {
alright. thanks again :)

I want the login button to be disabled while the user is waiting for the server to respond to the login request. this is why i made `waitingForServer`. to use that i needed `self` because it is set in `then(..)`. could i use `await` instead?

2021-01-27 14:26 UTC, kajdehoop requested changes

2021-01-27 14:26 UTC, kajdehoop commented on src/components/layout/LoginModal.vue
> +        this.$store.dispatch("user/login", {username, password, self}).then(result => {
I think `this.waitingForServer` can be used in the `then()`, as you've used an arrow function. You're also using `this.errorMessage` there so the `this.waitingForServer` should work in the same way. Correct me if I'm wrong though :) 

Btw another thing that I now see, you don't need to pass the event `e` to the methods and do preventDefault(). In vue you can do this by using the prevent modifier, for example `@click.prevent="login"`. Should work in the same way, but makes the code a bit cleaner and simpler 🙂 I also see that in the dialog watcher, you pass `d` into the function. I'm not 100% sure, but I think `d` is the value of the variable right? I would then just call it `value` or `val` to make it more clear.

2021-01-28 12:12 UTC, DenBaas commented on src/components/layout/LoginModal.vue
> +        password: "test",
Do you have the specific measurements/sizes or do you know where I can find it?

2021-01-28 13:16 UTC, kajdehoop commented on src/components/layout/LoginModal.vue
> +        password: "test",
Good question! Here are the most important ones:
Title fontsize: 20px
Text fontsize: 14px
Width modal: 365px
Height modal: 285px
Width inputfields: 200px
Height inputfields: 30px
Login button fontsize: 20px
Button color: #3A62A8

A padding on the modal of around 20-25px should be fine. I think the login button can be made a bit smaller (incl the fontsize), maybe 16px fontsize.

I'll see if for the new designs I can find a way to share them through Adobe XD so you can see the sizes of all elements :)

2021-01-28 14:42 UTC, DenBaas commented on src/components/layout/LoginModal.vue
> +        password: "test",
![afbeelding](https://user-images.githubusercontent.com/5918608/106153766-30a82980-617f-11eb-9b71-d8993daca080.png)
thanks! I created this now and I think the text is small. What do you think? The input fields don't match yet with the inputs in the modal to create a new role:
![afbeelding](https://user-images.githubusercontent.com/5918608/106153888-4fa6bb80-617f-11eb-800b-e15247ba993b.png)
i will still do that

2021-01-28 14:43 UTC, DenBaas commented on src/components/layout/LoginModal.vue
> +        this.$store.dispatch("user/login", {username, password, self}).then(result => {
thanks!

2021-01-29 17:57 UTC, kajdehoop approved these changes

2021-01-29 17:57 UTC, kajdehoop approved these changes

2021-01-29 17:58 UTC, kajdehoop approved these changes

2021-01-29 18:01 UTC, kajdehoop commented
Everything looks nice ^^ @SamLubbers I did the review, but see there are conflicts in package-lock.json and package.json. Could you review those two? Not completely sure what to do about them ;)

2021-01-30 15:28 UTC, aleesaan commented
I can pick it up from here Kaj! I also wanted to mention a few things 🤓

2021-01-30 18:46 UTC, aleesaan requested changes
Hey @DenBaas thank you so much for this PR!  
I'm leaving quite a lot of comments but don't get overwhelmed by the number, most of them are very simple changes (like removing some extra code), while in the rest of the comments I tried to leave sample codes (and link some relevant resources) to make it easier for you to implement them.  
Feel free to answer my comments and let me know if something isn't clear!

2021-01-30 18:46 UTC, aleesaan commented on src/store/index.ts
> +if (Vue.$cookies.isKey("loginToken")) {
I would move this initialization inside the `created` method in the main.ts file, where we initialize the Vue instance.

2021-01-30 18:46 UTC, aleesaan commented on src/store/modules/user.ts
> +      Vue.$cookies.set("loginToken", token, lifetime);
Instead of repeating this `"loginToken"` string (which can lead to errors), we create and export a const from the top of this file:

```ts
export const loginCookieKey = "loginToken";
```

Then we can use it in this file, as well as import it in other files as needed.

2021-01-30 18:46 UTC, aleesaan commented on src/store/index.ts
> +Vue.use(VueCookies);
This file is specific to the Vuex store, so I wouldn't add this here. We can instead move it to the main.ts file.

2021-01-30 18:46 UTC, aleesaan commented on src/store/modules/user.ts
> +Vue.use(VueCookies);
We don't need to call this here again, since we already call it elsewhere.

2021-01-30 18:46 UTC, aleesaan commented on src/store/modules/user.ts
> +    loggedIn(state) {
Can you revert this change? It's good to use arrow functions when possible, as they're provide a shorter syntax.

2021-01-30 18:46 UTC, aleesaan commented on src/store/modules/user.ts
> +    setTokenOnStart({ commit }): void {
What do you think of `initializeFromCookie` as the name? Also, you don't need to specify `: void`, as typescript already infers it automagically ✨

2021-01-30 18:46 UTC, aleesaan commented on src/store/modules/user.ts
> +    ): Promise<[boolean, string]> {
Same here, we don't need to specify the return type as it gets inferred! You can see this by removing it and then hovering on the function, you'll see that TS recognizes it correctly.

2021-01-30 18:46 UTC, aleesaan commented on src/store/modules/user.ts
> +        .then(function(res) {
Since you use `await` above, you don't need to use `then` here. This can become:

```ts

try {
  const { data } = await axios.post(
    process.env.VUE_APP_KEYSERVER_URL || "",
    qs.stringify(params),
    config
  );
  commit("setToken", data.access_token);
  commit("setTokenCookie", {
    token: data.access_token,
    lifetime: data.expires_in
  });
} catch ({ response }) {
  return response.data?.error_description || "Login server unavailable";
}
```
I dropped the `success` variable because it wasn't used outside this function. If everything goes smooth, we simply commit stuff, whereas if there's an error, we return it so it can  be shown to the user.

2021-01-30 18:46 UTC, aleesaan commented on src/styles/global.scss
> +      background-color: #3a62a8;
We don't need this, the button already uses the primary color.

2021-01-30 18:46 UTC, aleesaan commented on src/styles/global.scss
> +    input {
I think we can remove this declaration altogether, I don't see any difference without it.

2021-01-30 18:46 UTC, aleesaan commented on src/styles/global.scss
> +  span {
Can you leave an empty line before each new declaration?

2021-01-30 18:46 UTC, aleesaan commented on src/styles/global.scss
> +    text-align: center;
I think we can remove this and the `align-self` below, I don't see difference without them.

2021-01-30 18:46 UTC, aleesaan commented on src/styles/global.scss
> +  display: inline-block;
I think we can remove this, I don't see difference without it.

2021-01-30 18:46 UTC, aleesaan commented on src/styles/global.scss
> +  //padding: 0 20px 20px 20px;
Can you remove this?

2021-01-30 18:46 UTC, aleesaan commented on src/styles/global.scss
> +  v-input {
I don't see this declaration being used, can we drop it? Unless I'm missing something?

2021-01-30 18:46 UTC, aleesaan commented on src/styles/global.scss
> +    margin-bottom: 10px;
We have another `p` declaration below, can you move this there?

2021-01-30 18:46 UTC, aleesaan commented on src/styles/global.scss
> +    content: " \2573";//2715
Can you remove the comment here?

2021-01-30 18:46 UTC, aleesaan commented on src/styles/global.scss
> +    margin: 0;
I think we can drop `margin`, `flex-wrap`, and `justify-content` from here, I don't see any difference without them.

2021-01-30 18:46 UTC, aleesaan commented on src/styles/global.scss
> +    form {
We can drop these styles, they're not being used since the `form` isn't inside the `.container` element.

2021-02-01 08:41 UTC, DenBaas commented on src/components/TheAppBar.vue
> +import store from "../store";
loginmodal is used, store not. fixed it

2021-02-01 10:38 UTC, DenBaas commented on src/styles/global.scss
> +    input {
for some reason i need it

2021-02-01 10:41 UTC, DenBaas commented on src/components/layout/LoginModal.vue
> +        .dispatch("user/login", { username, password, self })
i removed it

2021-02-01 10:49 UTC, DenBaas commented on src/store/modules/user.ts
> +        .then(function(res) {
thanks! this works a lot better :)

2021-02-01 10:52 UTC, DenBaas commented on src/styles/global.scss
> +    text-align: center;
i need this here as well for some reason

2021-02-01 13:26 UTC, DenBaas commented on src/components/TheAppBar.vue
>      <v-btn v-else text @click.stop="logout">
I agree that the logic is mixed now and should be better. The logout button is here while the login button is in `LoginModal.vue`. Why should I not put it all in the login modal?

2021-02-01 13:31 UTC, DenBaas commented on .gitignore
> +.eslintrc.json
That file was created while setting up vscode so i added it since it is specific for me?

2021-02-01 13:41 UTC, aleesaan commented on src/components/TheAppBar.vue
>      <v-btn v-else text @click.stop="logout">
Indeed, that's also a possibility! But then it wouldn't be only a `LoginModal`, as it would contain also buttons and logic to open/close it, as well as logic to know whether you're authenticated or not (to show the right button). That's why I suggested the above, I think it provides a better separation of concerns - the `LoginModal` component will only contain/show the modal (and its contained logic), and the rest can be handled outside. What do you think?

2021-02-01 13:43 UTC, aleesaan commented on .gitignore
> +.eslintrc.json
I think you can safely remove both the file and this line, cause we use `.eslintrc.js` in this project (and we do need to track it, as it provides the linting rules for the project).

2021-02-01 14:31 UTC, DenBaas commented on src/components/TheAppBar.vue
>      <v-btn v-else text @click.stop="logout">
Well I think it is better to keep `loginModalOpen` in the login modal, so what `dialog` is now. I can rename that. I agree it is not nice that the login and logout button are now mixed so to solve it I want to put it in `LoginModal` because for me that is the easiest for me now. I like to keep everything together as much as possible so that means the login/logout functions should be together.

2021-02-04 20:25 UTC, aleesaan commented on package.json
> +    "axios": "^0.21.1",
There are still unneeded changes in the package.json (and package-lock.json), can you please have a look? Only keep the change for `vue-cookies`.

2021-02-04 21:06 UTC, aleesaan requested changes

2021-02-04 21:06 UTC, aleesaan commented on src/components/layout/AuthState.vue
> +      const message = await this.$store.dispatch("user/login", {
Can you call this `errorMessage` to be more explicit, and below directly check for `if (!errorMessage) { ... }`?

2021-02-04 21:06 UTC, aleesaan commented on src/components/layout/AuthState.vue
> +      this.username = ""; //kaj-dev
I think it would be better if we reset these properties after a successful login, rather than on `open()` - so that if you mistakenly close the modal, and reopen it, they're still there. I'd suggest the following:

- Remove the `open` method altogether, and directly do `@click="dialog = true"` in the template
- Create a `reset` method that resets username, password, serverLoading and errorMessage, and call it after a successful login
- Bonus, I'd remove the `close` method too, since it's only used once, and instead directly do:

```ts
if (!errorMessage) {
  this.dialog = false;
  this.reset();

  return;
}
```

2021-02-04 21:06 UTC, aleesaan commented on src/store/modules/user.ts
> +        if (e) {
This will never be true, cause `e` isn't a property that you can destructure from the error. Can you please have a look at my [previous comment](https://github.com/xrnl/aginun/pull/134#discussion_r567295654) about how we should do this?

2021-02-05 08:54 UTC, DenBaas commented on src/store/modules/user.ts
> +        if (e) {
idk why i changed it back. sorry!

2021-02-05 09:07 UTC, DenBaas commented on src/components/layout/AuthState.vue
> +    @click:outside="$emit('close')"
which one?

2021-02-05 09:13 UTC, DenBaas commented on src/store/modules/user.ts
> -        // eslint-disable-next-line @typescript-eslint/camelcase
i get this error here if i add it: `Definition for rule '@typescript-eslint/camelcase' was not found  @typescript-eslint/camelcase`

2021-02-08 15:15 UTC, SamLubbers commented on src/components/TheAppBar.vue
>      <v-btn v-else text @click.stop="logout">
@DenBaas hey I see that you've made a lot of progress with this pull request :raised_hands: I'll also share some of my feedback in the areas where I think it can help or where there is no agreement.

While I see that at first it can be easier to write all the related functionality in one place, when this is done continuously it leads to bloated functions/components that are doing too much functionality, making them more difficult to understand and reuse. To avoid these issues it's good to stick to important programming design principles such as the principle of [single responsibility](https://en.wikipedia.org/wiki/Single-responsibility_principle) & [modularity](https://en.wikipedia.org/wiki/Modular_programming). 

The suggestion from @aleesaan supports these principles:

* single responsibility: the modal component only has the logic to let a user input their credentials and login, and nothing else. With the code that he suggested, someone that reads `TheAppBar` will immediately see that there is one button, one modal and that the button controls the modal. When grouping all of that together it's not immediately obvious.
* modularity: since the component only has a modal, and not the buttons, it's more modular and more easily reusable and interchangeable. For example, if you want to activate the modal from a different place in mobile devices, you can easily do so, by adding a separate button on small screens (just like we do for the creation of new roles). Or if we like the button but want to replace the modal, we can just keep the buttons in the code and replace the modal with a different component.

I hope this clarifies Ale's suggestion a bit. Please share if you still have questions :ok_person:

2021-02-08 15:26 UTC, SamLubbers commented on src/styles/global.scss
> +    input {
hmm that's curious :sweat_smile: @DenBaas can you share what happens with/without this code?

2021-02-08 15:28 UTC, SamLubbers commented on src/styles/global.scss
> +    text-align: center;
@DenBaas here I'll share the same feedback as the other comment above. If you share what happens in your computer then we can try to reproduce it and understand why it is needed :ok_hand:

2021-02-08 15:31 UTC, SamLubbers commented on src/store/modules/user.ts
> -        // eslint-disable-next-line @typescript-eslint/camelcase
@DenBaas hmmm that's interesting. I think the issue might be that you have a newer version of `typescript-eslint`. [Here](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/camelcase.md) I see that the camelcase rule has been deprecated in favour of the naming-convention rule. Can you try using this rule instead?

2021-02-08 15:37 UTC, SamLubbers commented on src/components/layout/AuthState.vue
> +    @click:outside="$emit('close')"
@DenBaas I'll unresolve this conversation as I think there is still no conclusion on this one. If you implement the feedback you can mark it as resolved, but if you don't it's useful if you share why you think the suggestion doesn't need to be implemented. That way each person reviewing the code has a good understanding of why something has/hasn't be incorporated into the code :nerd_face:

2021-02-08 15:52 UTC, SamLubbers commented on src/store/modules/user.ts
> -        // eslint-disable-next-line @typescript-eslint/camelcase
Actually I see now in the `package.json` that you've upgraded the `@typescript-eslint/eslint-plugin` package. That's probably leading to the error. Like Ale say's [here](https://github.com/xrnl/aginun/pull/134#discussion_r567262955) it is best if you don't upgrade the packages in this pull request and only add the one new package you've added.

2021-02-08 16:03 UTC, aleesaan commented on src/store/modules/user.ts
> -        // eslint-disable-next-line @typescript-eslint/camelcase
Good catch, I think this might fix the issue indeed!

2021-02-08 17:33 UTC, SamLubbers requested changes
Hey @DenBaas, thank you for implementing all of this functionality :raised_hands: I can imagine it was a looooot of work, especially considering you joined the project not too long ago!

I first reviewed the existing comments in the code and added my feedback where it was relevant. Then I went through the entire code to add some additional feedback, so that you can also get some of my insights and not just Ale's :stuck_out_tongue_winking_eye: 

Besides the feedback that I've left in the code, the last thing that I'd like to add is that it would be great to have tests for the new `AuthState` component and for the updated functionality in `store/user.ts`. This might be a bit too much for in this pull request, so it might be better if you can make a new issue so that we make sure we write tests for it in the future :nerd_face:

2021-02-08 17:33 UTC, SamLubbers commented on src/components/layout/AuthState.vue
> +        this.username.trim().length == 0 ||
Actually, what will work even better would be to use [vee-validate](https://vee-validate.logaretm.com/v3/guide/basics.html) in order to perform the validation of the input fields. I suggest you read through the basics of the documentation and then implement the validation for the username and password field. Not only will it check for many more conditions with fewer code, but it will also makes it easy to determine the [validation state](https://vee-validate.logaretm.com/v3/guide/state.html) so that you can disable a button when the fields are not valid. 

In the [Vuetify documentation](https://vuetifyjs.com/en/components/forms/#vee-validate) you can also see good examples on how you can use vee-validate with Vuetify to provide nice error messages with Vuetify components.

2021-02-08 17:33 UTC, SamLubbers commented on src/components/layout/AuthState.vue
> +      serverLoading: false
I see that you use a `serverLoading` prop to disable the button on submit. This is already very useful to show the user that they cannot log in again :ok_hand: To make it even better I would include a spinner to show the user that the application is loading and that they need to wait. We already have the [saeris/vue-spinners](https://github.com/saeris/vue-spinners) package installed, which makes it really easy to add nice looking spinners

2021-02-08 17:33 UTC, SamLubbers commented on src/components/layout/AuthState.vue
> +    <template v-slot:activator="{}">
Using the v-slot:activator is only necessary when you use the `{ on }` functionality to trigger opening the dialog

```vue
      <template v-slot:activator="{ on, attrs }">
        <v-btn
          color="red lighten-2"
          dark
          v-bind="attrs"
          v-on="on"
        >
          Click Me
        </v-btn>
      </template>
```
When you use a separate function you can just keep the button outside. I personally think this is clearer, because at the top level you will have a button to trigger the modal, and then the modal itself.

2021-02-11 14:19 UTC, DenBaas commented on package.json
> +    "axios": "^0.21.1",
i checked out `package.json` and `package-lock.json` to the version on the master and installed `vue-cookies` and the build works now. is it correct now?

2021-02-11 14:25 UTC, DenBaas commented on src/store/modules/user.ts
> +    loggedIn(state) {
i reverted it now!

2021-02-11 14:29 UTC, DenBaas commented on src/styles/global.scss
> +    input {
well i'm implementing the vuetify components now and this css can be removed. i will show the differences next time

2021-02-11 14:30 UTC, DenBaas commented on src/styles/global.scss
> +    text-align: center;
thanks. same as in the other comment :)

2021-02-11 14:33 UTC, DenBaas commented on src/components/layout/AuthState.vue
> +        this.username.trim().length == 0 ||
thanks! i think i got it correct now. a new issue now is that error messages are weirdly translated:
![afbeelding](https://user-images.githubusercontent.com/5918608/107650073-66203d00-6c7e-11eb-92c7-8d62dffd4f99.png)
what should i do with this?

2021-02-11 14:36 UTC, DenBaas commented on src/components/layout/AuthState.vue
> +    @click:outside="$emit('close')"
we talked about it in private. it turned out that `@click:outside` was not necessary because the modal closes when clicking outside of the modal without this line.

2021-02-12 11:07 UTC, DenBaas commented on package.json
> +  "homepage": "https://github.com/DenBaas/aginun#readme"
it is deleted now. idk how it got here haha

2021-02-12 11:17 UTC, DenBaas commented on src/styles/global.scss
> +#login-modal {
i still have the css for the close button because i think it is the most clean solution. i tried adding it with rows but then the title is not centered anymore. do you have a solution or can i just keep it like that?

2021-04-07 10:28 UTC, aleesaan commented
Closing this PR because of inactivity, I will open a new one to finalize this case.

2021-04-07 10:28 UTC, closed without merging