Multlingual input
xrnl/aginun pull request #141
Opened 2021-02-15 19:20 UTC by aleesaan

## What changes have been made? 
Created a multi-language input to enable multilingual roles.

### Issues resolved by these changes
Related to #103, but I first want to get the multilingual input to work.

2021-03-03 07:24 UTC, SamLubbers requested changes
@aleesaan what an insanely big improvement on the translations :star_struck: It doesn't only work almost perfectly, but the code is also so clean and well organised. 

These are the last things that I've seen that we need to change:

- [x] unable to press enter in the text areas. This would be useful so that
  people can write lists. 
- [ ] when a role is published, and the user clicks on new role, the
multilingual data from the previous role is still there. The current
`resetState` doesn't seem to clear the data for the translatable fields. 
- [x] show dutch as the first language, since the majority of people in the
movement have a preference for dutch. 
- [ ] imagine someone starts filling in a role in both languages and then
decides that they only want it in dutch. In that case, even if they de-select
the language, the data of both languages is still sent, and therefore still
appears when searching for roles. What is the best way to fix it? 1) delete the data of the unselected language before sending it to the backend? 2 have a field for each role specifying the languages for which the role should be displayed? I personally think that option 1 is better because option 2 will increase the complexity of the code to display roles.

A few last things that I need to fix in the backend:

- [x] send the selected language to search_roles (through a header)
- [x] do not show roles in a certain language if there is no data for that language
- [x] do not display an individual role view for roles that don't exist in that
  language. This might happen if people find a dutch only role in the dutch
  version of the page, share the URL, and someone else tries to see the role
  from their english version of the page.
- [ ] set multilingual data in backend for working circles, and display the correct language in all parts of the application.

2021-03-03 07:24 UTC, SamLubbers commented on src/components/MultiLanguageInput.vue
> +        <template v-slot:label>🇬🇧 {{ $t("Dutch") }}</template>
```suggestion
        <template v-slot:label>🇳🇱 {{ $t("Dutch") }}</template>
```

2021-03-03 07:24 UTC, SamLubbers commented on src/components/roles/RoleEditDialog.vue
> +            rules="required"
I would add the rules it had before. This prevents people from entering extremely long titles that don't fit in the role overview card. Also it's good to prevent special characters from appearing in the title.
```suggestion
            rules="required|alpha_spaces|max:30"
```

2021-03-03 07:24 UTC, SamLubbers commented on src/components/roles/RoleEditDialog.vue
> +    return i18n.t("This field is required.");
Wow what a massive clean up of the validation :clap: :clap: When I wrote the previous code I think I was a bit too excited about passing the field names to the error messages :laughing:

2021-03-03 18:26 UTC, aleesaan commented on src/components/roles/RoleEditDialog.vue
> +    return i18n.t("This field is required.");
😂

2021-03-07 15:45 UTC, SamLubbers requested changes
@aleesaan thanks so much for the last fixes. We're almost there!! :grin: There are a few last things to fix:

- [ ]  Currently when you enter multiple lines in the role description,
  responsibilities or requirements, they appear as one line in the
  `RoleViewDialog`. They should be rendered as multiple lines
- [ ] Currently, when you select no application deadline (`dueDate`), it is set
  to the current date. It should instead publish `dueDate` as `null` if no
  dueDate is selected. 
- [ ] When you edit a role the first time the right data appears in the form.
  But when you edit a role, click publish and then try to edit it again you
  won't see the role details anymore, instead it appears as a new role. 

I've also left some questions/suggestions in the code

2021-03-07 15:45 UTC, SamLubbers commented on package-lock.json
> +    "vue-loader-v16": {
why did this file get updated? :thinking:

2021-03-07 15:45 UTC, SamLubbers commented on src/components/MultiLanguageInput.vue
> +      (this.$refs.en_form as InstanceType<typeof ValidationProvider>).reset();
This code throws the following error if you publish a language with only one selected role. 

```
Error in callback for watcher "value": "TypeError: this.$refs.nl_form is undefined"
```

I think a simple if statement could fix it

2021-03-07 15:45 UTC, SamLubbers commented on src/components/roles/RoleEditDialog.vue
> +        translation &&
out of curiosity, why is this line needed? Isn't it possible to directly return the result of ` Object.entries(translation)...`?

2021-03-07 15:45 UTC, SamLubbers commented on src/components/MultiLanguageInput.vue
>        this.internalValue[key] = value;
I think we can do this without having an `interalValue` variable:

1. clone `this.value` into `const newValue`
2. set `newValue[key] = value;`
3. `this.$emit("input", newValue);`

This way you can remove `this.internalValue = value;` within the watch statement, and directly read the data from `value`. `:value="value.en"`

2021-03-09 17:01 UTC, aleesaan commented on package-lock.json
> +    "vue-loader-v16": {
Not sure, probably related to the other dependency you added - I now deleted the node_modules + package-lock and did a fresh `npm i`; there's still a bunch of changes in the package-lock but I wouldn't worry as long as everything works fine.

2021-03-28 16:49 UTC, SamLubbers submitted a review, later dismissed
@aleesaan with your and my last couple of commits all the issues (that we know of) are now resolved :partying_face: 

Now the edit role form always works well and the right working circle colours are loaded from the backend. If you want you can test it one more time and if there are no more big issues you can merge it :raised_hands:

2021-03-28 20:18 UTC, SamLubbers approved these changes

2021-03-28 20:49 UTC, merged