Login modal and token in cookie
xrnl/aginun pull request #150
Opened 2021-04-17 09:04 UTC by aleesaan

### Issues resolved by these changes
Resolves #121 and #122.

## Additional comments
Follow-up for the [PR 134](https://github.com/xrnl/aginun/pull/134), which was closed due to inactivity.

2021-04-20 15:11 UTC, SamLubbers requested changes
@aleesaan thanks for implementing these two pull requests :raised_hands: :100: And thanks again for all the work you put into improving the previous pull request that fixed these issues.

The functionality works exactly like it should :ok_hand: I log in and out without a problem and I remain logged in even after refreshing the page.

I just left some comments in the code about small things that can be improved. On top of that, I think it would be good to display the `FeedbackAlert` when a user successfully logs in and out. Especially when logging out it happens really fast and some feedback would be useful to let the user know that it worked.

2021-04-20 15:11 UTC, SamLubbers commented on src/components/AuthState.vue
> +                  :error-messages="errors.length ? errors : serverError"
I see that the `serverError` is now displayed in the password field. The issue that this creates is that it could make the user think that the problem is with the password, when in fact the problem could be the username. A better solution is to display some red text with the `serverError` either above or below the fields, or using a `FeedbackAlert`

2021-04-20 15:11 UTC, SamLubbers commented on src/store/modules/user.ts
> +      }
I thought that this would handle case 1 of issue #147, but when I change the endpoint of the auth server this error doesn't appear and instead an error appears in the console. If you can get this error handling to work then we could also close #147 with this PR

2021-04-27 11:27 UTC, aleesaan commented on src/store/modules/user.ts
> +      }
Done ✌️

2021-04-27 14:38 UTC, SamLubbers approved these changes
Everything works flawlessly :sparkler: Thanks @aleesaan!

I've just made the issue #154 so that we don't forget to clear the default user when deploying on production.

2021-04-27 14:38 UTC, merged