Feature/new layout filter 156
xrnl/aginun pull request #157
Opened 2021-05-03 10:11 UTC by tomootes

## What changes have been made? 

**Before**: the button hangs still at the top:
![Schermafbeelding 2021-05-03 om 12 02 59](https://user-images.githubusercontent.com/4222167/116864078-92a57e80-ac07-11eb-84cc-282dcae57f67.png)

**After**: the button hangs at the bottom:
![Schermafbeelding 2021-05-03 om 11 50 29](https://user-images.githubusercontent.com/4222167/116864084-93d6ab80-ac07-11eb-823a-f058252d25dd.png)

**Before**: here the back button in the filter is difficult to find:
![Schermafbeelding 2021-05-03 om 12 03 14](https://user-images.githubusercontent.com/4222167/116864246-d9937400-ac07-11eb-8c3e-b10fba750469.png)

** After **: here the back button is located at the bottom and easier to find:
![Schermafbeelding 2021-05-03 om 11 50 38](https://user-images.githubusercontent.com/4222167/116864291-eca64400-ac07-11eb-964b-962231dff0c3.png)

## Rationale for these changes

- It was very unclear for users how to filter the search results.
- Both buttons were located at the top, which is harder to tap for mobile users.

### Issues resolved by these changes

Resolves #156 

## Additional comments

Quite straightforward!

2021-05-03 10:13 UTC, tomootes commented
Im sorry but some changes in this feature branch were meant for resolving #130. Maybe we can resolve this one first after reviewing #130 again.

2021-05-09 16:13 UTC, SamLubbers reviewed
@tomootes these are great changes :raised_hands: See the [comments on Mattermost](https://organise.earth/xr-netherlands/pl/trf9f5qysfrb9cqdbgxf9ymf9o) for feedback from me and Ale. Next time you want some feedback on a pull request you can just send a link to that pull request on Mattermost. That way we don't duplicate conversations across platforms.

And which changes were fixes intended for #153? If you want we can already merge this branch into that one so that it has all of your latest fixes.

2021-05-13 15:44 UTC, SamLubbers requested changes
@tomootes thank you so much for implementing the feedback so quickly :zap: The new design is great!! :fire: 

There is only a couple of small things that I would change and that can be done quite quickly:

1. Allow users to select multiple local groups or working groups. Before we used `v-autocomplete` so that users could find roles within multiple local groups or working groups, which is very useful in case someone is interested in roles in more than one group. I think that with these changes (using `v-select`), users can only select one group at a time.
2. Disable (but do not hide) the "remove filters" button: this is more a suggestion than a requirement. I think that if a certain button cannot be used, we should still show it and disable it, instead of hiding it completely. I think this makes the interface more consistent and provides less surprises.

2021-05-14 08:03 UTC, tomootes commented
> @tomootes thank you so much for implementing the feedback so quickly ⚡ The new design is great!! 🔥
> 
> There is only a couple of small things that I would change and that can be done quite quickly:
> 
> 1. Allow users to select multiple local groups or working groups. Before we used `v-autocomplete` so that users could find roles within multiple local groups or working groups, which is very useful in case someone is interested in roles in more than one group. I think that with these changes (using `v-select`), users can only select one group at a time.
> 2. Disable (but do not hide) the "remove filters" button: this is more a suggestion than a requirement. I think that if a certain button cannot be used, we should still show it and disable it, instead of hiding it completely. I think this makes the interface more consistent and provides less surprises.

hi @SamLubbers its been a pleasure man 🌱

2021-05-17 19:45 UTC, SamLubbers approved these changes
@tomootes WOHOOO this branch is now ready to be merged :tada: I'll rebase from master and skip the commits included in #152 in order to resolve the merge conflicts :sunglasses:

2021-05-17 19:54 UTC, merged