Filters in URL
xrnl/aginun pull request #163
Opened 2021-05-27 19:15 UTC by aleesaan

### Issues resolved by these changes
#26 

## Additional comments
For some reason the `v-range-slider` emits the `@end` event twice, which results in an error for a double navigation in the console. I'll try to look more into it (suggestions from reviewers are welcome!), and if I can't find anything I'll just add a `catch` for that error.

2021-05-30 10:17 UTC, SamLubbers requested changes
@aleesaan what a well-crafted clean change :star2: (as always :wink:) Throughout the code I've sprinkled some specific tokens of appreciation.

I've only identified one issue and one question

### Issues 

The working group and local group filters in the URL should use the group name instead of the internal ID in the database because this ID might change. If we use the id people might get different results if something in the database changes, but if we use the group name then they'll always get the results for the groups they want to filter by.

### Questions

Currently when I enter an invalid URL parameter it shows all roles (as it should), but it keeps the parameter in the URL. Is this what we want? Or do we want to remove invalid parameters from the URL?

2021-05-30 10:17 UTC, SamLubbers commented on src/router/index.ts
> +  },
Nice that you're redirecting to roles instead of using an alias. This makes the URL behaviour consistent and predictable

2021-05-30 10:17 UTC, SamLubbers commented on src/components/roles/RoleViewDialog.vue
> +      @keydown.escape="$router.back()"
Great that you've fixed this by using the correct Vue Router function :raised_hands: Using the Vuex URL stack properly will avoid some nasty errors in the future :100:

2021-05-30 10:17 UTC, SamLubbers commented on src/styles/components/_nav-bar.scss
> +        background: $xr-green-light;
I also noticed this last time hehe. Good that you fixed it :sunglasses:

2021-05-30 10:17 UTC, SamLubbers commented on src/store/modules/roles.ts
> -      });
What an amazing simplification of the code :sparkles: :100:

2021-05-30 10:17 UTC, SamLubbers commented on tests/unit/store/roles.spec.ts
> +        expect(commit).toBeCalledWith("setDefaultFilters");
Once again, amaaazing that you've also implemented tests for your changes (and simplified the tests so much)

2021-05-31 18:42 UTC, aleesaan commented
Awesome to hear 🚀  
To answer your points:

> ### Issues
> The working group and local group filters in the URL should use the group name instead of the internal ID in the database because this ID might change. If we use the id people might get different results if something in the database changes, but if we use the group name then they'll always get the results for the groups they want to filter by.

I disagree, we should always rely on IDs for this stuff, the name isn't reliable for two reasons: it can change in different languages (e.g. den Haag vs the Hague for a local group), and it could change over time (e.g. a working group changing name). The database's IDs should never change, if anything we'd add more groups into a new ID; but even if it did, the change would be reflected in the filters, so the correct group would be selected!

> ### Questions
> Currently when I enter an invalid URL parameter it shows all roles (as it should), but it keeps the parameter in the URL. Is this what we want? Or do we want to remove invalid parameters from the URL?

Good idea! I added the logic to clear the extra params in my last commit ✌️

2021-06-01 15:12 UTC, SamLubbers approved these changes
@aleesaan good point about the names of groups in different languages! I didn't consider that one. I'm sold :wink:

2021-06-01 15:12 UTC, merged