fix: querying wrt time
xrnl/aginun pull request #209
Opened 2021-06-15 12:47 UTC by ShubhamPalriwala

### Issues resolved by these changes

Resolves #179

2021-06-15 13:12 UTC, SamLubbers requested changes
Hey @ShubhamPalriwala congratulations with you first pull request :tada: The suggestion I had commented in the issue doesn't actually solve the problem. In your code I've suggested the code change that will do the trick :wink: 

I hope you can make it to the [meeting in a few hours](https://github.com/xrnl/aginun/blob/master/CONTRIBUTING.md#join-project-meetings) :crossed_fingers: Then we can meet each other and help you find interesting issues :call_me_hand:

2021-06-15 13:12 UTC, SamLubbers commented on src/GraphQL/roles.ts
> +          { timeCommitmentMax: { _gte: $timeCommitmentMin } }
```suggestion
          {
            _or: [
              { timeCommitmentMax: { _lte: $timeCommitmentMax } }
              { timeCommitmentMin: { _gte: $timeCommitmentMin } }
            ]
          }
```

2021-06-15 15:19 UTC, ShubhamPalriwala commented
@SamLubbers Thanks for the help!

I'm really sorry but I have my end-semester exams this week so will not be able to join for the weekly meeting this time.

But would love to join for the next one and help fix some bugs and make the platform better

2021-06-15 17:15 UTC, SamLubbers requested changes
@ShubhamPalriwala you're almost there! Now you've added the new filter but not removed the old one. If you remove the old time commitment filter it should work :ok_hand: 

Did you test the changes locally? Then you would have probably seen that it doesn't work exactly as it should. Let me know if you need help with getting the application to run locally :pray: :seedling: 

And no worries about not joining the meeting! Good luck with your exam week :muscl

2021-06-17 12:25 UTC, ShubhamPalriwala commented
@SamLubbers, I've made the requested changes and sorry for the number of 3 commits, It'd be better if you squashed and then merged it so that it's simple and easy to understand in the main branch.

2021-06-17 18:07 UTC, SamLubbers approved these changes
@ShubhamPalriwala no worries! We have commit squashing enabled by default when merging a pull request :sunglasses: 

I will now approve & merge. Congratulations with your first contribution to the project :tada: :partying_face:

2021-06-17 18:07 UTC, merged