Feature/jv local hasura
xrnl/aginun pull request #211
Opened 2021-06-15 17:28 UTC by jurcello

## What changes have been made? 

A docker compose file is added for hasura so it can run locally. The env.example file is updated so it uses this local instance.

## Rationale for these changes

### Issues resolved by these changes

Resolves #175 

## Additional comments

If you want to test this, you need to add the VUE_APP_HASURA_SERVER_URL variable from the .env.example file to your loacl env file.

2021-06-27 21:02 UTC, SamLubbers requested changes
@jurcello thank you for this huge & amazing change :star_struck: :100: :zap:

The new setup works almost perfectly! I managed to get the local development backend working, and for the front-end to connect to the backend :raised_hands: 

I've shared most of my feedback in the code. They're all very small changes, but they're a lot. I think the easiest way to review my feedback is to go to the `files changed` tab and go through each file one by one. Here I'll also share some general feedback:

## Feedback

## Questions

How can I access the frontend when I running the production application locally? I tried going to `localhost:80` but it didn't work. I think I have some crucial ngnix knowledge lacking here. (I did manage to get the production docker-compose working with `docker-compose --file docker/docker-compose-production.yml up -d`

2021-06-27 21:28 UTC, aleesaan commented on docker/init_db.sql
> +\.
Why not? I think it would be good to have some roles there when running the app the first time, unless maybe I'm misunderstanding something here?

2021-06-27 21:45 UTC, SamLubbers commented on docker/init_db.sql
> +\.
@aleesaan the idea is that we can also use this for production, so that if we run the script the application starts off with no roles. But this shouldn't be a problem during development! This file is only loaded once. Every other time that you start the backend the sql init file isn't loaded and you use the existing data in the db (with any roles you might have created)

But... if you think we'll waste a lot of time creating manual roles, we could make a separate SQL script to seed our development database with roles if we wish to do so. If this is something you would want you can make a new issue and I can implement this pretty easily :ok_hand:

2021-06-27 21:51 UTC, aleesaan commented on docker/init_db.sql
> +\.
Ah I see! Then yes I'd say to create a script to setup some initial data, it can be useful for us during development to have a few different roles - I'll create the issue.  
And thanks @jurcello for such an awesome PR!! I'm slowly trying to go through it even though I'm not very familiar with this stuff :)

2021-06-28 08:22 UTC, jurcello commented on .env.production.example
> +VUE_APP_HASURA_SERVER_URL=http://api.volunteer.extinctionrebellion.local/
Not really. The api runs on the server, which is not localhost in production, but the api url. I did make the same mistake, but then realised that the frontend connects to a remote backend.

2021-06-28 08:25 UTC, jurcello commented on README.md
> +5. Install [docker desktop](https://www.docker.com/products/docker-desktop)
That's better indeed. I thought docker compose would be in docker now, but apparently that's only for non-linux.

2021-06-28 08:28 UTC, jurcello commented on docker/Dockerfile
> +COPY ./dist /usr/share/nginx/html
That's a good observation. I would not build in the target container though. I will add a build container step, so the final container doesn't contain all the (unnecessary) source files.

2021-06-28 08:36 UTC, jurcello commented on docker/default.conf
> +    proxy_pass http://graphql-engine-prod:8080;
This is rather counter intuitive, and actually has nothing to do with nginx. If you use docker compose, each service runs in it's own container. There is a shared network between these containers. The host 'graphql-engine-prod' resolves to the hasura container. Localhost will not work, as on the nginx container only nginx is running.

2021-06-28 08:50 UTC, jurcello commented on docker/docker-compose-production.yml
> +  postgres-prod:
Hmm,  I guess you are right. The reason that I changed the names was that somehow my local docker would get confused between the production and non-production file. I will try to change the names back and find out what was the problem.

2021-06-28 08:56 UTC, jurcello commented on docker/docker-compose-production.yml
> +    - "8080:8080"
The reason that it's 8000 in local configuration is the fact that vue also runs on port 8080 by default. 
In production I left it on 8080 because that seems to be the default. There is however not a valid reason why they should not be the same, so I will set the port on production to 8000 as well.

Also I will expos the graphql engine.

2021-06-28 08:58 UTC, jurcello commented on docker/docker-compose-production.yml
> +    - "frontend"
Absolutely correct. I will fix it.

2021-06-28 09:05 UTC, jurcello commented on docker/docker-compose.yml
> +    - "5432:5432"
You are right. I will fix it.

2021-06-28 09:08 UTC, jurcello commented on docker/docker-compose.yml
> +      - "8000"
We can use any port we want. I'll make ik 8008.

2021-06-28 09:08 UTC, jurcello commented on docker/docker-compose.yml
> +      HASURA_GRAPHQL_ADMIN_SECRET: D!G!TALREBELL1on
I agree.

2021-06-28 09:10 UTC, jurcello commented on package.json
> +    "docker:stop": "docker compose --file docker/docker-compose.yml stop"
At my computer docker is complaining that docker-compose is deprecated as it is included in docker itself. That's why I use `docker compose` without the dash. Is that different on linux?

2021-06-28 09:11 UTC, jurcello commented on src/plugins/vue-apollo.ts
> +const baseUrl = process.env.VUE_APP_HASURA_SERVER_URL;
That's a good suggestion. I will have a look at it.

2021-06-28 11:44 UTC, jurcello commented
@SamLubbers In reply on your comment on env variables: you are absolutely right about the secrets that should not be committed to code.

I would like to discuss the sharing of the env variable. In my opinion this might cause confusion: the env file would contain values only for vue or docker. Because the only variable we share might be the port of the backend, and this variable doesn't need to change normally, I would suggest we have different env files for clarity.

2021-06-28 12:32 UTC, jurcello commented on docker/docker-compose.yml
> +    - ./init_db.sql:/docker-entrypoint-initdb.d/init.sql
I tried the change, but it didn't work: the filename cannot be removed from the directory because that would mean trying to mount a file to directory path, which doesn't work.

I changed the filename to init.sql though.

2021-06-28 12:33 UTC, jurcello commented on docker/docker-compose.yml
> +      HASURA_GRAPHQL_ADMIN_SECRET: D!G!TALREBELL1on
I tried but apparently this password cannot be removed: the container immediately stops. I now added the password in the env file.

2021-06-28 12:34 UTC, jurcello commented on docker/docker-compose.yml
> +      HASURA_GRAPHQL_ADMIN_SECRET: D!G!TALREBELL1on
` Fatal Error: --unauthorized-role (HASURA_GRAPHQL_UNAUTHORIZED_ROLE) requires --admin-secret (HASURA_GRAPHQL_ADMIN_SECRET) or  --access-key (HASURA_GRAPHQL_ACCESS_KEY) to be set and is not allowed when --auth-hook (HASURA_GRAPHQL_AUTH_HOOK) is set`

2021-06-28 13:57 UTC, jurcello commented
In answer to your questions:

**How can I access the frontend when I running the production application locally?**

In the production env the variable `VUE_APP_HASURA_SERVER_URL` is defined. If you use the example it is:
`VUE_APP_HASURA_SERVER_URL=http://api.volunteer.extinctionrebellion.local/`

To be able to run the code locally, you have to add the host (`api.volunteer.extinctionrebellion.local`) to your hosts file (`/etc/hosts`)
The entry looks like this:

`127.0.0.1 volunteer.extinctionrebellion.local api.volunteer.extinctionrebellion.local`

The api is reachable by appending `api` in front of the url. The proxy passes these requests to hasura.

**Do you already know how we will handle database migrations? For example, if I add a column to a table in my local Hasura instance, how can we ensure that everyone also gets that new table in their own local instance?**

I think we need to create a new ticket for this. This might take some time to find out.

2021-06-28 13:58 UTC, jurcello commented on docker/docker-compose-production.yml
> +      VIRTUAL_HOST: 'volunteer.extinctionrebellion.dev'
This variable is not needed so I removed it.

2021-06-29 07:53 UTC, SamLubbers commented on src/plugins/vue-apollo.ts
> +const baseUrl = process.env.VUE_APP_HASURA_SERVER_URL;
In that case let's keep it simple. With our current setup this error shouldn't occur.

2021-06-29 07:56 UTC, SamLubbers commented on .env.production.example
> +VUE_APP_HASURA_SERVER_URL=http://api.volunteer.extinctionrebellion.local/
oh yeah of course, nice catch!

2021-06-29 08:02 UTC, SamLubbers commented on package.json
> +    "docker:stop": "docker compose --file docker/docker-compose.yml stop"
I just found out that it is indeed different. On Linux docker-compose requires a separate installation, and the `compose` command isn't available with docker. What is the best way to solve this? Could we have an npm script that runs one command or another depending on the OS? :thinking: 

Also, it would be good to update the readme instructions with this detail (if you're using Linux use `docker-compose` instead of `docker compose` (in the build section)

2021-06-29 08:06 UTC, SamLubbers commented on docker/init_db.sql
> +\.
@jurcello we can remove this code for now. Ale has made a new issue to properly implement this in the future :ok_hand:

2021-06-29 08:08 UTC, SamLubbers reviewed
@jurcello thanks for implementing all these changes so quickly and for answering all my questions so clearly :raised_hands: I have gone through all the comments and you've resolved almost everything :100: 

There are only two unresolved conversations (which you can find by going to `files changed > conversations`. Besides that, we only need to incorporate points 1 & 2 of the `documentation` section in my previous review.

2021-07-22 09:40 UTC, jurcello commented on docker/init_db.sql
> +\.
I removed the data.

2021-07-22 09:42 UTC, jurcello commented on package.json
> +    "docker:stop": "docker compose --file docker/docker-compose.yml stop"
I changed it back to docker-compose

2021-07-24 10:43 UTC, SamLubbers approved these changes
@jurcello thank you so much for resolving the last comments & figuring out all the production configuration, and even deploying the application :star_struck: With this PR, you didn't only resolve #175, but you also resolved #48, #176




I just left a few comments with a small minor questions, but I'll already approve & merge this PR as it's working perfectly :fire: 

Lastly, I found a few improvements to the backend security, but we can implement that at some other point: #220

2021-07-24 10:45 UTC, merged