New styling + coloured cards
xrnl/aginun pull request #77
Opened 2020-08-12 11:44 UTC by tomootes

## What changes have been made? 

If you have changed the interface please include screenshots of before and after. 

## Rationale for these changes

### Issues resolved by these changes

Resolves #... 

## Additional comments

Please explain difficult parts of your code to make it easier to review your pull request.

2020-08-25 11:15 UTC, tomootes commented on src/views/RolesOverview.vue
> +    </div> -->
Check! I removed the text here

2020-08-25 11:17 UTC, tomootes commented on src/styles/variables.scss
> -// Variables for specific components must come before the import
I agree! I added this at the bottom.

2020-08-25 11:18 UTC, tomootes commented on src/styles/variables.scss
> +$heading-font-family: "Times New Roman", Times, serif;
Check. I added this from an example i think. It is overwritten elsewhere. Removed it.

2020-08-25 11:26 UTC, tomootes commented on src/components/TheAppBar.vue
> +      <img src="https://extinctionrebellion.nl/app/uploads/2019/02/XR-NL-Black.svg" class="img-fluid" alt="" width="155.49" height="76.02">
Made an .svg file for the logo. I agree on using the plain logo! A lot more suitable for applications in my opinion.

2020-08-25 11:27 UTC, tomootes commented on src/components/TheAppBar.vue
> +    </v-btn> -->
Since i love cleaning up code,  i agree.

2020-08-25 11:43 UTC, tomootes commented on src/components/surfaces/DefaultCard.vue
> +.v-card {
It feels kind of weird to store colours in the store since we can use SCSS for this. Im personally a fan of keeping the styling within the SCSS as much as possible. I moved the colour classes to /styles/base/_colours.scss, i hope this is OK for now. Maybe we can discuss this the next call?

2020-08-25 11:46 UTC, tomootes commented on src/store/modules/styles.js
> +    navbarHeight: "91px",
I agree! Probably works better on mobile in general. Changed it back to 64px in combination with the new logo.

2020-08-25 11:48 UTC, tomootes commented on src/styles/base/_colours.scss
> +$theme-colors: (
Yessss, i found them here: [xr-website](https://github.com/xrnl/extinction-rebellion-nl/blob/master/web/app/themes/xrnl/assets/sass/_variables.scss).

2020-08-25 11:59 UTC, tomootes commented on src/styles/base/_colours.scss
> +$blue-light: #ceebf8;
I took the colours directly from https://rebellion.global/news/#blog. I don't now how to exactly reproduce the colours on this page using a SCSS function. If we want to figure this out we we would have to reach out to the global website team i think. Maybe refactor this later as the project grows?

2020-08-25 12:02 UTC, tomootes commented
@SamLubbers i pushed a new version which takes your comments into account 📦

2020-08-29 06:59 UTC, SamLubbers commented on src/styles/base/_colours.scss
> +$blue-light: #ceebf8;
@tomootes that's ok with me, but in that case it would be good to leave a comment explaining how these lighter variations are obtained, and that we aim to calculate lighter and darker variations dynamically using scss functions like [color.scale()](https://sass-lang.com/documentation/modules/color#scale)

2020-08-29 07:30 UTC, SamLubbers requested changes
Hey @tomootes, thank you for implementing the changes and sorry I wasn't able to review your pull request before 🙏 

The application looks much better with the XR symbol and the code is already a lot cleaner 🔥 

I think last time I left so many comments that you might have missed some of them 😅 In particular, I refer to [this comment](https://github.com/xrnl/aginun/pull/77#discussion_r470543049) and the few that follow.

These final change should take no time. Once they're implemented I'll merge the new design. I'm excited 🤩

2020-08-29 07:30 UTC, SamLubbers commented on src/styles/base/_colours.scss
> +$blue-light: #ceebf8;
@tomootes that's ok with me, but in that case it would be good to leave a comment explaining how these lighter variations are obtained, and that we aim to calculate lighter and darker variations dynamically using scss functions like [color.scale()](https://sass-lang.com/documentation/modules/color#scale)

2020-08-29 07:30 UTC, SamLubbers commented on src/styles/base/_colours.scss
> +}
Right now it's not entirely clear from the class name what this class does. I think it would be a good idea to rename each of these to `.bg-{colour-name}`, [as they do in Bootstrap](https://getbootstrap.com/docs/4.3/utilities/colors/#background-color). Thus, this class would become `bg-blue-light`, the next one `bg-yellow-light` and so on. If you change this, make sure to also change the class names in `RoleCard` so the classes still work 😇

2020-08-29 07:30 UTC, SamLubbers commented on src/components/surfaces/DefaultCard.vue
> +.v-card {
@tomootes yes you're right, all the styling should stay within the SCSS. I forgot for a second that you can also make `scss` globally available by adding it to the generic scss files 😅 Thanks for moving this to `_colours.scss` 👌

2020-08-29 07:30 UTC, SamLubbers commented on src/styles/base/_colours.scss
> +}
Also, you can make all of these classes dynamically with `scss` instead of having to manually write them out. This makes the code more maintainable and much easier to create future similar classes (like `btn-green-light`) for example. 

I looked into the Bootstrap source code and they create their classes dynamically with this code:

```scss
@each $color, $value in $theme-colors {
  @include bg-variant(".bg-#{$color}", $value);
}

@mixin bg-variant($parent, $color) {
  #{$parent} {
    background-color: $color !important;
  }
  a#{$parent},
  button#{$parent} {
    @include hover-focus {
      background-color: darken($color, 10%) !important;
    }
  }
}
```

2020-08-31 13:50 UTC, tomootes commented on src/components/roles/RoleCard.vue
> +    getColour: function(workingCircle) {
I do agree, this is much more semantic. Fixed it ⚡

2020-08-31 14:00 UTC, tomootes commented on src/components/roles/RoleCard.vue
> +}
Removed it and added the class to the tag.

2020-08-31 14:03 UTC, tomootes commented on src/styles/variables.scss
> +// $color-pack: false;
I commented this out due to debugging. I don't use any of the standard colours from Vuetify. I enabled the boolean again.

2020-08-31 14:11 UTC, tomootes commented on src/styles/base/_typography.scss
> +@import url('https://fonts.googleapis.com/css?family=Crimson+Text');
Check!

2020-08-31 14:26 UTC, tomootes commented on src/styles/base/_typography.scss
> +}
I spent quite some time on getting `$heading-font-family` getting to work in variabless.scss. Sadly i couldn't get it to work and I let it be. For now my suggestion is to have it hang around until somebody is going to implement more styling on the typography.

2020-08-31 14:28 UTC, tomootes commented on src/styles/global.scss
> +  box-shadow: none;
I do have to make a confession here. I don't like material design all that much. Its very useful and i must admit it can be very empowering for usability, but it also creates an internet thats an 'eenheidsworst'. Since all other XR' websites don't use box-shadow on buttons, i propose to not use it.

2020-09-01 08:26 UTC, tomootes commented on src/styles/base/_colours.scss
> +}
Great idea 💯  I implemented this along with the `lighten()` function.

2020-09-01 08:33 UTC, tomootes commented
@SamLubbers no worries! We all have to deal with multithreaded life. 

I resolved all your comments and i'm happy with the result. Maybe its good to make documentation available on the styling/ colours on the web to prevent problems like we ran into. But then we would have to reach out to the other tech teams as well. I'm looking forward to delivering the application!

2020-09-02 11:56 UTC, SamLubbers commented on src/styles/global.scss
> +  box-shadow: none;
Good point to keep the style in line with other XR websites. 

And yes let's not become part of the eenheidsworst. At first, we had to settle for a pre-existing material design because we didn't have any designers in our team, but now that you're part of the team you can keep on improving the design to match's XR's idiosyncrasy ✨

2020-09-02 12:18 UTC, SamLubbers approved these changes
@tomootes everything looks great! Especially the new `colours.scss` code is so concise and reusable 💯 💯 💯 

I only found a minor bug with the current card design, but I made a new issue for that so we can resolve it in the future #84

I will resolve the merge conflicts and then merge 🎊

2020-09-02 13:29 UTC, SamLubbers commented
@tomootes I messed up massively... 

I tried resolving your merge conflicts using the Github tool. After resolving those conflicts, it merged the master branch into your branch, which is not what I expected to happen. I just expected Github to commit the changes to the files for which I had resolved the conflicts. I tried to undo this commit by doing a hard reset to your latest commit, and force pushing that to your repository. To my surprise, it didn't reset your repository to your latest commit, but to the latest commit on master. This means that all the changes you made have been removed from your repository. 😟 😰 

Luckily I made a local copy, which I have now merged into master. You can find the code with all your changes [here](https://github.com/xrnl/aginun/commit/d76c9dd8c7012192c8b8375a7e1784b0b6e72633). 

Still, I don't like this solution because [git thinks](https://github.com/xrnl/aginun/graphs/contributors) that I have written all the code that you've actually written. I'm going to see if it's possible to fix this.

2020-09-02 14:28 UTC, SamLubbers commented
If you want your changes to be reflected, we can do the following

1. Push your local changes to your master branch. This should restore your commit history.
2. I'll reset the `xrnl:master` branch to the commit previous to your merge.
3. Merge the `xrnl:master` branch into your own branch to resolve merge conflicts. 
4. I can reopen this PR and merge your changes from Github.

2020-09-04 16:34 UTC, merged

2020-09-04 16:44 UTC, SamLubbers commented
@tomootes it worked!! 🎉  Git recognized your PR as if I had never messed it up. Now your changes are properly reflected in the [git history](https://github.com/xrnl/aginun/commits/master) and [project contributors](https://github.com/xrnl/aginun/graphs/contributors).

After your merge, I [fixed some minor issues](https://github.com/xrnl/aginun/commit/d1167fc5d147d7fea76820a62eb5342d08faf612). One of them is to keep prettier warnings on, so that we ensure the prettier style across all files that we edit. ✨