Add due date to role
xrnl/aginun pull request #99
Opened 2020-10-29 17:27 UTC by aleesaan

## What changes have been made? 

Added due date to role, as explained in issue #33.

### Issues resolved by these changes

#33 

## Additional comments
It's the first time I'm working with Vue / GraphQL so please correct me anywhere needed. I added some tests for the datepicker component but wasn't sure how to test the 'datepicking' part, if you have suggestions I'm all ears!
I also cleaned up a couple of lint errors and changed the `serve` script to `start`, so we can use `npm start`, hope that's ok 😅

2020-10-31 11:38 UTC, SamLubbers commented
@aleesaan thanks for implementing this feature and making the pull request 🙌 I'll review your code this weekend.

2020-11-01 19:04 UTC, SamLubbers requested changes
@aleesaan thank you for implementing this very necessary feature :raised_hands: I'm quite impressed that this is the first time you are using Vue.js. The application works exactly like expected :100: :sunglasses:  

## Suggestions

I only have a few minor suggestions, some mentioned in the code and some here:
  * `Due Date` is a useful term for internal use, but for users I think it would be more clear if we use the term `Application deadline`. The only two places to change this are in the role view and edit dialogue. 
  * I would rename `DatePickerCustom` with a more name that better explains the component, such as `DatePickerField`. If you change this don't forget to change the component `name` property, and the name of the component in `RoleEditDialog` and in the tests. 

## Testing

It's so great that you've already written the unit tests for the component you have created. This is very good practice to make sure the component works as expected and to easily detect breaking changes in the future. 

You've got the most important tests covered: verifying the component has the expected output text for the input props. Another important category of tests are those that verify the component produces the right outputs events as a result of user interactions. In this case, that would mean checking that the component emits the appropriate event (`this.$emit("update", new Date(date).toISOString());`) when the user selects a date (`@input="updateDate"`). You might be able to do this by:
  1. Manually showing the menu by setting `showMenu = True`
  2. Find a button corresponding to one day of the DatePicker. Something like this could work: `wrapper.find(".v-date-picker-table > .v-btn")`
  3. Trigger a click on that button
  4. Verifying the `update` event is emitted with the date in the right format. The `vue-test-utils` documentation should explain how this can be done.

Besides this, it's not necessary to verify specific aspects of the DatePicker (such that the calendar is displayed correctly), as this is specific to Vuetify and not specific to our application.

Thank you once again for this improvement and welcome as a new developer of the XR NL volunteer platform :green_heart: :partying_face:

2020-11-02 18:03 UTC, aleesaan commented on package.json
> +    "start": "vue-cli-service serve",
It's just a shortcut, as typing `npm start` is equivalent to `npm run start`. I will definitely update the `README.md`, though, thanks for mentioning it!

2020-11-02 18:06 UTC, aleesaan commented on src/components/DatePickerCustom.vue
> +    },
Sounds good to me, but how long? Maybe a week would also be good?

2020-11-02 18:06 UTC, aleesaan commented on src/components/DatePickerCustom.vue
> +        prepend-icon="mdi-calendar"
Done! Definitely don't mind, I was looking forward to naming / styling and any other such comments. I just tried to go with my guts trying to stick to what I saw in the code/UI, but I'm glad you mention this stuff.

2020-11-02 18:12 UTC, aleesaan commented
Good to hear it mostly looks good 🚀  I had tried getting that test you mentioned already before opening the PR, and tried again now, but I just can't get it to work (I also looked online, but nope)... I left a draft commented there, maybe you can also try to have a look, while I keep trying? I will then cleanup the tests file.

2020-11-03 07:35 UTC, SamLubbers commented on src/components/DatePickerCustom.vue
> +        prepend-icon="mdi-calendar"
@aleesaan at the moment we don't have clear UI guidelines, but we aim to eventually make the application look like [an XR application](https://rebellion.global/).

In terms of code style, we use Prettier so we have a [clear consistent enforceable style](https://prettier.io/docs/en/why-prettier.html). In addition, we also follow the principles outlined in the [Vue style guide](https://vuejs.org/v2/style-guide/). 

The good thing is that you don't have to remember any of these rules :relieved: If you have ESLint configured in your editor it will always highlight code that doesn't match the Prettier style of Vue style guide. And Prettier can automatically format the code when needed. If you don't have this set up yet, you can check out [our recommended setup](https://github.com/xrnl/aginun/wiki/Recommended-setup)

2020-11-03 07:38 UTC, SamLubbers commented on src/components/DatePickerCustom.vue
> +    },
Yes that could be good, but after thinking about it some more it might also be confusing for people why they can't select the other days. We can just leave this for now and when the platform is live see if this problem does indeed exist. We could easily do that by seeing which are the lowest values for `dueDate - createdDate`

2020-11-03 07:41 UTC, SamLubbers approved these changes
@aleesaan thank for incorporating the changes so quickly and it's so great to see that you got that last test working. At first these tests can take some time to figure out but it does get easier to write them the more you do it.

It also still works and the code looks good so it's ready to merge with the master branch. Congratulations with your first completed code contribution :tada:

2020-11-03 07:42 UTC, merged

2020-11-03 17:26 UTC, SamLubbers commented
@aleesaan one last tip :nerd_face: Next time you reference an issue you close use one of the [issue closing keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) so that the issue you solve is automatically closed when the pull request is merged.